# Generated by Django 4.0.5 on 2022-06-18 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1000)),
                ('context', models.CharField(max_length=2500)),
                ('model_name', models.CharField(max_length=250)),
                ('answer', models.JSONField(default=dict)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
