# Generated by Django 4.0.5 on 2022-06-18 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem',
            name='pub_date',
        ),
    ]
